name: CryptJavaPlugin
version: 1.0
main: me.Proba.crypt.CryptJavaPlugin

commands:
  givecrypt:
    description: Gives the player a crypt
    usage: /givecrypt <crypt_name>

  ability:
    description: Use crypt abilities
    usage: /ability <1|2>

  removecrypt:
    description: Removes all equipped crypts from the player
    usage: /removecrypt
